project_id = "hwbdlvmesabvmxommlcl"

[functions.verify-deployment]
verify_jwt = false

[functions.check-locker-ownership]
verify_jwt = false

[functions.verify-locker]
verify_jwt = false

[functions.affiliate-payout]
verify_jwt = false

[functions.verify-timelock]
verify_jwt = false

[functions.record-timelock-sale]
verify_jwt = false
